version: '3.8'

services:
  traefik:
    image: traefik:v3.1

    command:
      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedByDefault=false"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"

      # ⚠️ IMPORTANT : pas de redirection HTTP->HTTPS
      # => sinon ACME HTTP-01 challenge échoue

      # ACME Let's Encrypt
      - "--certificatesresolvers.le.acme.email=contact@hamsterdeal.ch"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"

      # Dashboard
      - "--api.dashboard=true"
      - "--log.level=INFO"

    ports:
      - published: 80
        target: 80
        protocol: tcp
      - published: 443
        target: 443
        protocol: tcp

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/traefik/letsencrypt:/letsencrypt

    networks:
      - traefik-net

    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"

        # Dashboard sécurisé HTTPS
        - "traefik.http.routers.dashboard.rule=Host(`traefik.hamsterdeal.ch`)"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.tls.certresolver=le"

networks:
  traefik-net:
    external: true
