name: Deploy Traefik (Docker Swarm)

on:
  workflow_dispatch:     # DÃ©ploiement manuel
  push:
    branches:
      - main          # DÃ©ploiement automatique pour la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH client
        run: sudo apt-get install -y sshpass

      - name: Deploy Traefik
        env:
          SSHPASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            echo "ðŸ“‚ Going to Traefik directory..."
            cd /home/${{ secrets.SSH_USER }}/traefik

            echo "â¬‡ Pulling latest Traefik config from Git..."
            git fetch --all
            git reset --hard origin/main

            echo "ðŸ³ Deploying Traefik stack..."
            sudo docker stack deploy -c docker-compose-traefik.yml traefik_stack

            echo "âœ… Traefik deployed successfully!"
          EOF
